# Generated by Django 4.2.11 on 2024-04-08 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='liked_by',
            new_name='like_users',
        ),
    ]
